### ISSUE TITLE
Limitations on ETH DID method

### ISSUE THREAD

**Issue by cbruguera** [uport-project/eth-did-resolver#2]
Hello, I think proposing `did:eth` as a simple DID representation for ethereum addresses is a great idea. However, I was just wondering about certain specifications of it as DID method, for instance "DID update" and "DID revocation", which if I'm not mistaken are part of the DID standard. 

Are there any thoughts on this matter? Also, any other relevant limitations we should consider for plain ethereum addresses to function as DIDs? Service endpoint definitions perhaps?...

If there're any other references of ongoing discussions on this regard, I'd appreciate any pointers. Thanks beforehand.

**Comment by coder5876** [comment]
@cbruguera This is a question about the definition of a DID - if the definition includes the ability to update the DID document then this would not technically be a DID since the DID document is fixed here. I believe there was some discussion on the Credentials Community Group mailing list about this but I don't remember if there was a solid conclusion.

**Comment by cbruguera** [comment]
@christianlundkvist thanks for your reply. From what I remember, at least Manu was in favor of flexibilizing the DID specs to include this "lightweight" cases, but probably there's still a consensus to be reached in this matter. I'm in favor of more flexible DID specs on this regard.
